Repository SUIN-BUNDANG-LINE/Frontend, pull requests merged in 2024-10, with the labels that each got.

#58 [SBL-132] 메인 페이지, 설문 상세 정보 페이지 컴포넌트 및 css 개선
  src/app/s/[surveyId]/page.tsx
  src/components/main/survey-finder/item/Item.module.css
  src/components/main/survey-finder/item/Item.tsx
  src/components/main/survey-finder/types.ts
  src/components/survey-details/Body.module.css
  src/components/survey-details/Body.tsx
  src/components/survey-details/Heads.module.css
  src/components/survey-details/Heads.tsx
  src/components/survey-details/index.tsx
  src/components/ui/tooltip/Tooltip.module.css
  src/services/surveys/types.ts
Labels: 기능구현

#59 [SBL-155] Workbench의 기본 정보 탭 리팩토링 및 썸네일 업로드 추가
  next.config.mjs
  package-lock.json
  src/app/workbench/[id]/tab0.module.css
  src/app/workbench/[id]/tab0.tsx
  src/components/workbench/basics/main-section/index.tsx
  src/components/workbench/basics/main-section/thumbnail.module.css
  src/components/workbench/basics/main-section/thumbnail.tsx
  src/components/workbench/basics/misc-section/index.module.css
  src/components/workbench/basics/misc-section/index.tsx
  src/components/workbench/basics/reward-section/finished-at.tsx
  src/components/workbench/basics/reward-section/index.module.css
  src/components/workbench/basics/reward-section/index.tsx
  src/components/workbench/basics/reward-section/list.module.css
  src/components/workbench/basics/reward-section/list.tsx
  src/components/workbench/basics/reward-section/max-participants.module.css
  src/components/workbench/basics/reward-section/max-participants.tsx
  src/components/workbench/basics/reward-section/reward-item.module.css
  src/components/workbench/basics/reward-section/reward-item.tsx
  src/components/workbench/basics/reward-section/type.module.css
  src/components/workbench/basics/reward-section/type.tsx
  src/components/workbench/basics/section.module.css
  src/services/ky-wrapper.ts
  src/services/s3/index.ts
  src/services/s3/types.ts
Labels: 기능구현, 리팩토링

#63 설문이용 v1.0.0 프론트엔드 배포 수정본
  src/components/workbench/ui/Header.tsx
Labels: 배포

#64 설문이용 v1.0.0 프론트엔드 배포 최종 수정본
  src/app/s/[surveyId]/layout.tsx
  src/components/management/result/PieChartComponent.tsx
  src/components/mypage/SurveyCreateButton.tsx
Labels: 배포

#65 설문이용 v1.0.0 프론트엔드 배포 마지막 수정본
  src/hooks/useCookie.ts
Labels: 배포

#66 HOTFIX: image upload 최적화 오류 수정(sharp 라이브러리 설치, swcMinify true)
  next.config.mjs
  package-lock.json
  package.json
Labels: 배포

#68 [SBL-167] 설문 삭제 버튼 추가, 기타 오류 수정
  src/app/(main)/mypage/page.module.css
  src/app/(main)/mypage/page.tsx
  src/app/layout.tsx
  src/components/workbench/ui/Header.module.css
  src/providers/auth/AuthProvider.tsx
  src/services/ky-wrapper.ts
  src/services/management/fetch.ts
Labels: 기능구현, 오류수정

#69 설문이용 v1.0.1 프론트엔드 배포
  public/assets/what_isvisible_does.png
  src/app/(main)/mypage/page.module.css
  src/app/(main)/mypage/page.tsx
  src/app/layout.tsx
  src/app/management/[id]/page.module.css
  src/app/management/[id]/page.tsx
  src/app/s/[surveyId]/p/page.tsx
  src/app/workbench/[id]/page.module.css
  src/app/workbench/[id]/page.tsx
  src/app/workbench/[id]/tab0.module.css
  src/app/workbench/[id]/tab1.module.css
  src/app/workbench/[id]/tab2.module.css
  src/app/workbench/[id]/tab2.tsx
  src/components/preview/ui/Participate/CheckboxField.module.css
  src/components/preview/ui/Participate/Field.module.css
  src/components/preview/ui/Participate/RadioField.module.css
  src/components/preview/ui/Participate/Section.module.css
  src/components/preview/ui/Ready/Message.module.css
  src/components/preview/ui/Ready/Message.tsx
  src/components/preview/ui/Ready/index.tsx
  src/components/survey-p/Section.module.css
  src/components/survey-p/farewell/Farewell.module.css
  src/components/survey-p/farewell/Farewell.tsx
  src/components/survey-p/ui/navigator/Navigator.module.css
  src/components/survey-p/ui/question/Question.module.css
  src/components/survey-p/ui/response/Option.module.css
  src/components/workbench/basics/main-section/thumbnail.module.css
  src/components/workbench/basics/main-section/thumbnail.tsx
  src/components/workbench/basics/misc-section/index.module.css
  src/components/workbench/basics/misc-section/index.tsx
  src/components/workbench/basics/reward-section/list.tsx
  src/components/workbench/basics/reward-section/reward-item.module.css
  src/components/workbench/basics/reward-section/reward-item.tsx
  src/components/workbench/ready/toc.module.css
  src/components/workbench/ui/Header.module.css
  src/components/workbench/ui/Header.tsx
  src/providers/auth/AuthProvider.tsx
  src/services/ky-wrapper.ts
  src/services/management/fetch.ts
Labels: 배포

#74 [SBL-200] 설문 통계 공개 기능 구현
  src/app/management/[id]/page.tsx
  src/app/management/[id]/tab0.tsx
  src/app/management/[id]/tab1.tsx
  src/app/management/[id]/tab2.tsx
  src/components/main/survey-finder/item/Item.tsx
  src/components/main/survey-finder/types.ts
  src/components/management/ui/Header.tsx
  src/components/survey-details/Body.module.css
  src/components/survey-details/Body.tsx
  src/components/survey-details/index.tsx
  src/components/workbench/basics/main-section/index.tsx
  src/components/workbench/basics/misc-section/index.tsx
  src/components/workbench/func/convert.ts
  src/components/workbench/func/index.ts
  src/components/workbench/service/fetch.ts
  src/components/workbench/store/index.ts
  src/components/workbench/types/query.ts
  src/components/workbench/types/store.ts
  src/services/participant/fetch.ts
  src/services/participant/index.ts
  src/services/result/fetch.ts
  src/services/result/index.ts
  src/services/result/types.ts
  src/services/surveys/types.ts
Labels: 기능구현

#81 [SBL-222] 엑셀 export 기능 추가
  package-lock.json
  package.json
  src/app/management/[id]/tab0.tsx
  src/components/management/result/FilterManager.module.css
  src/components/management/result/FilterManager.tsx
  src/components/management/result/PieChartComponent.module.css
  src/services/result/fetch.ts
  src/services/result/types.ts
Labels: 기능구현
