Repository SUIN-BUNDANG-LINE/Frontend, pull requests merged in 2024-08, with the labels that each got.

#10 [SBL-57] 추첨 기능 추가
  src/app/layout.tsx
  src/app/s/[surveyId]/p/page.tsx
  src/app/s/[surveyId]/result/page.tsx
  src/components/layout/main/Header.module.css
  src/components/layout/main/Header.tsx
  src/components/social-login/Container.tsx
  src/components/survey-p/Section.module.css
  src/components/survey-p/Section.tsx
  src/components/survey-p/SectionBlock.tsx
  src/components/survey-p/drawing/Board.module.css
  src/components/survey-p/drawing/Board.tsx
  src/components/survey-p/drawing/Drawing.module.css
  src/components/survey-p/drawing/Drawing.tsx
  src/components/survey-p/drawing/Phone.module.css
  src/components/survey-p/drawing/Phone.tsx
  src/components/survey-p/farewell/Farewell.module.css
  src/components/survey-p/farewell/Farewell.tsx
  src/components/survey-p/hooks/useForm.ts
  src/components/survey-p/ui/navigator/Navigator.module.css
  src/components/survey-p/ui/navigator/Navigator.tsx
  src/components/survey-p/ui/question/Question.module.css
  src/components/survey-p/ui/question/Question.tsx
  src/components/survey-result/index.module.css
  src/components/survey-result/index.tsx
  src/components/ui/button/Button.module.css
  src/components/ui/button/Button.tsx
  src/services/drawing/fetch.ts
  src/services/drawing/index.ts
  src/services/drawing/types.ts
  src/utils/misc.ts
Labels: 기능구현

#12 [SBL-59] Frontend 프로덕션 서버 배포 CD 파이프라인 구축
  .github/workflows/prod_deploy.yml
Labels: 환경설정

#14 설문이용 프론트엔드 1차 배포 수정본
  .github/workflows/prod_deploy.yml
Labels: 배포

#21 프론트엔드 수정 사항 배포
  src/app/globals.css
  src/app/s/[surveyId]/draw/page.module.css
  src/app/s/[surveyId]/draw/page.tsx
  src/app/s/[surveyId]/layout.tsx
  src/app/s/[surveyId]/p/page.tsx
  src/app/s/[surveyId]/page.tsx
  src/components/main/survey-finder/SurveyFinder.tsx
  src/components/main/survey-finder/control/Pagination.module.css
  src/components/survey-details/index.tsx
  src/components/survey-p/drawing/Board.module.css
  src/components/survey-p/drawing/Board.tsx
  src/components/survey-p/drawing/Drawing.tsx
  src/components/survey-p/drawing/Phone.module.css
  src/components/survey-p/drawing/Phone.tsx
  src/components/survey-p/funcs/storage.ts
  src/components/survey-p/ui/question/Question.module.css
  src/components/survey-p/ui/question/Question.tsx
  src/components/survey-result/index.module.css
  src/components/survey-result/index.tsx
  src/components/ui/dropdown/Dropdown.tsx
  src/components/ui/error/Error.module.css
  src/components/ui/error/Error.tsx
  src/services/drawing/fetch.ts
  src/services/ky-wrapper.ts
  src/services/surveys/index.ts
Labels: 배포

#22 [SBL-86] 프론트엔드 배포를 docker로 하도록 수정
  .dockerignore
  .github/workflows/prod_deploy.yml
  dockerfile
Labels: 오류수정, 환경설정

#23 프론트엔드 배포를 docker로 하도록 수정
  .dockerignore
  .github/workflows/prod_deploy.yml
  dockerfile
Labels: 배포

#36 v0.1.0 프론트엔드 배포 수정본
  src/components/survey-p/Section.module.css
  src/components/survey-p/ui/response/Option.module.css
  src/components/survey-p/ui/response/Option.tsx
Labels: 배포
